### ISSUE TITLE
Base dependency is outdated

### ISSUE THREAD

**Issue by asoltysik** [zcourts/Dish#2]
The package currently checks for `base <= 4.7`. It is the only package I have found that implemented 128-bit murmur3.

@zcourts

**Comment by zcourts** [comment]
Happy to take PR changing the base package check. If not, I'll try to get some time to update and publish

**Comment by asoltysik** [comment]
Done, I've also run `stack init` on it.

**Comment by zcourts** [comment]
I've published `0.0.0.6`. The upper bound is required on cabal packages. I wasn't able to publish with just the changes in your PR, it wouldn't pass hackage validation. I've set the upper bound on `base` and `bytestring` to their current versions.
